version: '3'

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: admin
            POSTGRES_USER: admin
        ports:
            - "5432:5432"
